#include:
#  - docker-compose.tasks.yaml  # Include tasks configuration

services:
  # Application service
  farm:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "${FARM_PORT}:${FARM_PORT}"
    networks:
      - security_net
    depends_on:
      - suricata

  # Reverse proxy / Load balancer
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - security_net
    ports:
      - "80:80"
    depends_on:
      - suricata
      - modsecurity
      - farm

  # IDS/IPS
  suricata:
    image: jasonish/suricata:latest
    network_mode: "host"
    volumes:
      - ./suricata/logs:/var/log/suricata:rw
      - ./suricata/rules:/etc/suricata/rules:rw
      - ./suricata/suricata.yaml:/etc/suricata/suricata.yaml:rw
    environment:
      - SURICATA_OPTIONS=-vvv --af-packet -i any
    command: -c /etc/suricata/suricata.yaml --af-packet -i any -v
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
      - IPC_LOCK
    restart: unless-stopped

  # WAF (ModSecurity)
  modsecurity:
    image: owasp/modsecurity-crs:nginx
    networks:
      - security_net
    volumes:
      - ./modsecurity/rules:/etc/modsecurity.d/rules:ro

  # Network monitoring
  caronte:
    image: ghcr.io/eciavatta/caronte:latest
    networks:
      - security_net
    depends_on:
      - mongo
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "${CARONTE_PORT}:3333"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./caronte/rules:/rules:ro  # Custom rules directory
    restart: unless-stopped

  # Database for logs
  mongo:
    image: mongo:4.4
    networks:
      - security_net
    volumes:
      - mongo_data:/data/db

  # WAF (ModSecurity) for tasks
  #modsecurity_tasks:
  #  image: owasp/modsecurity-crs:nginx
  #  networks:
  #    - security_net
  #  depends_on:
  #    - tasks  # Assuming 'tasks' is defined in docker-compose.tasks.yaml
  #  volumes:
  #    - ./modsecurity/rules:/etc/modsecurity.d/rules:ro
  #  ports:
  #    - "8081:80"  # Different port from main WAF

networks:
  security_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"

volumes:
  mongo_data:

